services:
  dnsmasq:
    image: alpine:3@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: ["sh", "-c", "apk add --no-cache dnsmasq && dnsmasq -d -C /etc/dnsmasq.conf"]
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - tftp-data:/var/lib/tftpboot:ro
    depends_on:
      ipxe-copy:
        condition: service_completed_successfully
    restart: unless-stopped

  nginx:
    image: nginx:alpine@sha256:db35bfc6b2951e7f8a72db5db120288c127ffaeeb4a6d4b95a26fead017d5913
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./boot.ipxe:/usr/share/nginx/html/boot.ipxe:ro
      - ./assets:/usr/share/nginx/html/assets:ro
      - ./config:/usr/share/nginx/html/config:ro
    restart: unless-stopped

  ipxe-copy:
    image: alpine:3@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: ["cp", "/src/snponly.efi", "/tftpboot/snponly.efi"]
    volumes:
      - ./snponly.efi:/src/snponly.efi:ro
      - tftp-data:/tftpboot

volumes:
  tftp-data:
