# See cp-11 for the busPath rationale.
machine:
  install:
    diskSelector:
      busPath: /pci0000:00/0000:00:17.0/*
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: cp-12.cluster.internal
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.10.1
searchDomains:
  disableDefault: false
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.10.229
link: enp3s0
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp3s0
addresses:
  - address: 192.168.10.232/24
routes:
  - gateway: 192.168.10.1
